; https://docs.unrealengine.com/5.2/en-US/lumen-performance-guide-for-unreal-engine/
; 0=Low, 1=Medium, 2=High, 3=Epic, 4=Cinematic

[PS5 DeviceProfile]

; shadow quality
+CVars=sg.ShadowQuality=2

; Set Lumen GI and reflection quality to High, targeting 60 fps
+CVars=sg.GlobalIlluminationQuality=2
+CVars=sg.ReflectionQuality=2

; Use SSR in lieu of Lumen reflections for perf
+CVars=r.Lumen.Reflections.Allow=0

; async compute
+CVars=r.LumenScene.Lighting.AsyncCompute=1
+CVars=r.Lumen.DiffuseIndirect.AsyncCompute=0
+CVars=r.Lumen.Reflections.AsyncCompute=0

+CVars=r.Lumen.AsyncCompute=1

; Nanite
+CVars=r.Nanite.Streaming.AsyncCompute=1

; hardware raytracing
+CVars=r.Lumen.HardwareRayTracing=0

; dynamic resolution, DynRes
; enable in Blueprints
+CVars=r.DynamicRes.OperationMode=1
+CVars=r.DynamicRes.MinScreenPercentage=50
+CVars=r.DynamicRes.MaxScreenPercentage=100
; 60 fps
+CVars=r.DynamicRes.FrameTimeBudget=16.6

; temporal super resolution
+CVars=r.TSR.AsyncCompute=2
; no need to manually set screen percentage (only if not using DynRes)
;+CVars=r.ScreenPercentage=50