; https://docs.unrealengine.com/5.2/en-US/lumen-performance-guide-for-unreal-engine/

[PS5 DeviceProfile]

; Set Lumen GI and reflection quality to High, targeting 60 fps
; 0=Low, 1=Medium, 2=High, 3=Epic, 4=Cinematic
+CVars=sg.GlobalIlluminationQuality=2
+CVars=sg.ReflectionQuality=2

; Use SSR in lieu of Lumen reflections for perf
+CVars=r.Lumen.Reflections.Allow=0

; async compute
r.LumenScene.Lighting.AsyncCompute=1
r.Lumen.DiffuseIndirect.AsyncCompute=0
r.Lumen.Reflections.AsyncCompute=0