; https://docs.unrealengine.com/5.2/en-US/lumen-performance-guide-for-unreal-engine/
; 0=Low, 1=Medium, 2=High, 3=Epic, 4=Cinematic

[PS5 DeviceProfile]
DeviceType=PS5
BaseProfileName=PS5_Base
bIsVisibleForAssets=False
+CVars=r.vsync=0
+CVars=t.maxfps=-1
+CVars=sg.ShadowQuality=2
+CVars=sg.GlobalIlluminationQuality=2
+CVars=sg.ReflectionQuality=2
+CVars=r.Lumen.Reflections.Allow=0
+CVars=r.LumenScene.Lighting.AsyncCompute=1
+CVars=r.Lumen.DiffuseIndirect.AsyncCompute=0
+CVars=r.Lumen.Reflections.AsyncCompute=1
+CVars=r.Lumen.AsyncCompute=0
+CVars=r.ReflectionCaptureResolution=64
+CVars=r.Nanite.Streaming.AsyncCompute=1
+CVars=r.RayTracing=0
+CVars=r.RayTracing.UseTextureLod=1
+CVars=r.RayTracing.Skylight=1
+CVars=r.RayTracing.Shadows=1
+CVars=r.RayTracing.GlobalIllumination.ScreenPercentage=50
+CVars=r.RayTracing.Culling=3
+CVars=r.RayTracing.Culling.Radius=15000
+CVars=r.RayTracing.Culling.Angle=0.5
+CVars=r.Lumen.HardwareRayTracing=0
+CVars=r.DynamicRes.OperationMode=1
+CVars=r.DynamicRes.MinScreenPercentage=50
+CVars=r.DynamicRes.MaxScreenPercentage=100
+CVars=r.DynamicRes.FrameTimeBudget=16.6
+CVars=r.TSR.AsyncCompute=2
+CVars=r.Lumen.DiffuseIndirect.SSAO=1
+CVars=r.Lumen.ScreenProbeGather.ShortRangeAO=0

[PS5_Base DeviceProfile]
DeviceType=PS5
BaseProfileName=
bIsVisibleForAssets=True
-CVars=r.RayTracing.Shadows=0
-CVars=r.RayTracing.AmbientOcclusion=0
-CVars=r.RayTracing.SkyLight=0
-CVars=r.RayTracing.GlobalIllumination=0
-CVars=r.RayTracing.Translucency=0
-CVars=r.RayTracing.Reflections=-1
-CVars=r.RayTracing.Reflections.ExperimentalDeferred=1
-CVars=r.RayTracing.Reflections.ExperimentalDeferred.MipBias=1
-CVars=r.RayTracing.Reflections.ExperimentalDeferred.GenerateRaysWithRGS=0
-CVars=r.RayTracing.Reflections.ExperimentalDeferred.SpatialResolve=1
-CVars=r.RayTracing.Reflections.ExperimentalDeferred.SpatialResolve.TemporalWeight=0.95
-CVars=r.RayTracing.Reflections.ScreenPercentage=40
-CVars=r.Reflections.Denoiser=0
-CVars=r.RayTracing.AsyncBuild=1
-CVars=sg.AntiAliasingQuality=1
-CVars=r.TSR.AsyncCompute=2
-CVars=r.TemporalAA.Upsampling=1
-CVars=r.DynamicRes.OperationMode=2
-CVars=r.DynamicRes.MinScreenPercentage=50
-CVars=r.DynamicRes.MaxScreenPercentage=74.07
-CVars=r.Nanite.ViewMeshLODBias.Offset=0.4330 ; = -log2(r.DynamicRes.MaxScreenPercentage / 100)
-CVars=r.Nanite.ViewMeshLODBias.Min=-0.5670 ; = r.Nanite.ViewMeshLODBias.Offset - 1
-CVars=r.Bloom.AsyncCompute=1
-CVars=r.Bloom.ScreenPercentage=25
+CVars=r.RayTracing.Shadows=0
+CVars=r.RayTracing.AmbientOcclusion=0
+CVars=r.RayTracing.SkyLight=0
+CVars=r.RayTracing.GlobalIllumination=0
+CVars=r.RayTracing.Translucency=0
+CVars=r.RayTracing.Reflections=-1
+CVars=r.RayTracing.Reflections.ExperimentalDeferred=1
+CVars=r.RayTracing.Reflections.ExperimentalDeferred.MipBias=1
+CVars=r.RayTracing.Reflections.ExperimentalDeferred.GenerateRaysWithRGS=0
+CVars=r.RayTracing.Reflections.ExperimentalDeferred.SpatialResolve=1
+CVars=r.RayTracing.Reflections.ExperimentalDeferred.SpatialResolve.TemporalWeight=0.95
+CVars=r.RayTracing.Reflections.ScreenPercentage=40
+CVars=r.Reflections.Denoiser=0
+CVars=r.RayTracing.AsyncBuild=1
+CVars=sg.AntiAliasingQuality=1
+CVars=r.TSR.AsyncCompute=2
+CVars=r.TemporalAA.Upsampling=1
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.MinScreenPercentage=50
+CVars=r.DynamicRes.MaxScreenPercentage=74.07
+CVars=r.Nanite.ViewMeshLODBias.Offset=0.4330 ; = -log2(r.DynamicRes.MaxScreenPercentage / 100)
+CVars=r.Nanite.ViewMeshLODBias.Min=-0.5670 ; = r.Nanite.ViewMeshLODBias.Offset - 1
+CVars=r.Bloom.AsyncCompute=1
+CVars=r.Bloom.ScreenPercentage=25

