[Windows DeviceProfile]

; shadow quality
+CVars=sg.ShadowQuality=2

; Set Lumen GI and reflection quality to High, targeting 60 fps
+CVars=sg.GlobalIlluminationQuality=2
+CVars=sg.ReflectionQuality=2

; Use SSR in lieu of Lumen reflections for perf
+CVars=r.Lumen.Reflections.Allow=0

; async compute, does not work on Windows ?
r.LumenScene.Lighting.AsyncCompute=1
r.Lumen.DiffuseIndirect.AsyncCompute=0
r.Lumen.Reflections.AsyncCompute=0