[Windows DeviceProfile]
DeviceType=Windows
BaseProfileName=
bIsVisibleForAssets=True

; shadow quality
+CVars=sg.ShadowQuality=3

; Set Lumen GI and reflection quality to High, targeting 60 fps
+CVars=sg.GlobalIlluminationQuality=3
+CVars=sg.ReflectionQuality=2

; Lumen
+CVars=r.Lumen.Reflections.RadianceCache=1

; async compute
+CVars=r.LumenScene.Lighting.AsyncCompute=1
+CVars=r.Lumen.DiffuseIndirect.AsyncCompute=0
+CVars=r.Lumen.Reflections.AsyncCompute=1

+CVars=r.Lumen.AsyncCompute=1

; Nanite
+CVars=r.Nanite.Streaming.AsyncCompute=1

; hardware raytracing
+CVars=r.Lumen.HardwareRayTracing=1
+CVars=r.Lumen.HardwareRayTracing.AsyncCompute=1
+CVars=r.Lumen.Reflections.HardwareRayTracing=1

; dynamic resolution, DynRes
; enable in Blueprints
+CVars=r.DynamicRes.OperationMode=1
+CVars=r.DynamicRes.MinScreenPercentage=80
+CVars=r.DynamicRes.MaxScreenPercentage=100
; 60 fps
+CVars=r.DynamicRes.FrameTimeBudget=16.6

; temporal super resolution
+CVars=r.TSR.AsyncCompute=2
; no need to manually set screen percentage (only if not using DynRes)
;+CVars=r.ScreenPercentage=80