[Windows DeviceProfile]
DeviceType=Windows
BaseProfileName=
bIsVisibleForAssets=True

+CVars=r.vsync=0
+CVars=t.maxfps=-1

; shadow quality
+CVars=sg.ShadowQuality=3

; Set Lumen GI and reflection quality to High, targeting 60 fps
+CVars=sg.GlobalIlluminationQuality=2
+CVars=sg.ReflectionQuality=2

; Lumen
+CVars=r.Lumen.Reflections.RadianceCache=1

; async compute
+CVars=r.LumenScene.Lighting.AsyncCompute=1
+CVars=r.Lumen.DiffuseIndirect.AsyncCompute=0
+CVars=r.Lumen.Reflections.AsyncCompute=1

+CVars=r.Lumen.AsyncCompute=0
+CVars=r.ReflectionCaptureResolution=128

; Nanite
+CVars=r.Nanite.Streaming.AsyncCompute=1

; raytracing
+CVars=r.RayTracing=1
+CVars=r.RayTracing.UseTextureLod=0
+CVars=r.RayTracing.Skylight=0
+CVars=r.RayTracing.Shadows=0

+CVars=r.RayTracing.GlobalIllumination.ScreenPercentage=50

+CVars=r.RayTracing.Culling=3
+CVars=r.RayTracing.Culling.Radius=15000
+CVars=r.RayTracing.Culling.Angle=0.5

; hardware raytracing
+CVars=r.Lumen.HardwareRayTracing=0
+CVars=r.Lumen.HardwareRayTracing.AsyncCompute=0
+CVars=r.Lumen.Reflections.HardwareRayTracing=0

; no dynamic resolution on Windows

; temporal super resolution
+CVars=r.TSR.AsyncCompute=2
; no need to manually set screen percentage (only if not using DynRes)
;+CVars=r.ScreenPercentage=80